### ISSUE TITLE
does taffydb support "groupby" and "having" ? 

### ISSUE THREAD

**Issue by foreverwithmalli** [typicaljoe/taffydb#135]
I dont see anything related to groupby in the documentation.

**Comment by typicaljoe** [comment]
It does not, mostly because it would be difficult to guarantee speed with a generic groupby and having methods. You can however roll your own. In most similar cases I call db().each() with a function that either inserts or increments counters inside of another db.

Something like:

`var groupByState = TAFFY();`

`people().each(function(r) {`
`    var thisGroup - groupByState({state:r.state});`
`    if (thisGroup.count()) {`
`        thisGroup.update({total:thisGroup.first().total+1});`
`   } else {`
`        thisGroup.insert({state:r.state,total:1})`
`   }`
`})``
