### ISSUE TITLE
Does sort actually work?

### ISSUE THREAD

**Issue by everythingability** [typicaljoe/taffydb#173]
Hi,

i was just playing with taffydb and in this code I'd expect the sort() function to work, but it doesn't seem to.

https://editor.p5js.org/remarkability/sketches/9NFvQDZNH

Tom

**Comment by realto619** [comment]
I had a similar issue on my testing, but I solved it by combining the sort with the forEach loop:

Instead of calling them separately:
**`products.order("price asc");`**
**`products.each(...`**

Call them together (also note that instead of the normal "asc", the documentation shows it as "asec")
**`products().order("price asec").each(function (r) { ... });`**

[Working Example](https://codepen.io/Realto619/pen/mdWQbLO) 

Hope that helps!
